services:
  - type: web
    name: GrandMaster
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000

databases:
  - name: grand-master-db
    plan: free